embed_assets: on

javascripts:

  image_upload:
    - public/javascripts/iframe_upload.js
    - app/views/articles/upload_iframe.jst

  image_preview:
    - public/javascripts/image_preview.js
    - public/javascripts/util.js

  subtitle_field:
    - app/views/subtitles/subtitle_form.jst
    - public/coffeescripts/subtitle_field.js

  subtitle_view:
    - public/coffeescripts/subtitle_view.js

  subtitle_tagging:
    - public/coffeescripts/subtitle_tag.js

  create_default_tag:
    - public/coffeescripts/create_default_tag.js

