embed_assets: on

javascripts:

  image_upload:
    - public/javascripts/iframe_upload.js
    - app/views/articles/upload_iframe.jst

  image_preview:
    - public/javascripts/image_preview.js
    - public/javascripts/util.js

