require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SubtitlesController do

  def mock_subtitle(stubs={})
    @mock_subtitle ||= mock_model(Subtitle, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all subtitles as @subtitles" do
      Subtitle.stub(:all) { [mock_subtitle] }
      get :index
      assigns(:subtitles).should eq([mock_subtitle])
    end
  end

  describe "GET show" do
    it "assigns the requested subtitle as @subtitle" do
      Subtitle.stub(:find).with("37") { mock_subtitle }
      get :show, :id => "37"
      assigns(:subtitle).should be(mock_subtitle)
    end
  end

  describe "GET new" do
    it "assigns a new subtitle as @subtitle" do
      Subtitle.stub(:new) { mock_subtitle }
      get :new
      assigns(:subtitle).should be(mock_subtitle)
    end
  end

  describe "GET edit" do
    it "assigns the requested subtitle as @subtitle" do
      Subtitle.stub(:find).with("37") { mock_subtitle }
      get :edit, :id => "37"
      assigns(:subtitle).should be(mock_subtitle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created subtitle as @subtitle" do
        Subtitle.stub(:new).with({'these' => 'params'}) { mock_subtitle(:save => true) }
        post :create, :subtitle => {'these' => 'params'}
        assigns(:subtitle).should be(mock_subtitle)
      end

      it "redirects to the created subtitle" do
        Subtitle.stub(:new) { mock_subtitle(:save => true) }
        post :create, :subtitle => {}
        response.should redirect_to(subtitle_url(mock_subtitle))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subtitle as @subtitle" do
        Subtitle.stub(:new).with({'these' => 'params'}) { mock_subtitle(:save => false) }
        post :create, :subtitle => {'these' => 'params'}
        assigns(:subtitle).should be(mock_subtitle)
      end

      it "re-renders the 'new' template" do
        Subtitle.stub(:new) { mock_subtitle(:save => false) }
        post :create, :subtitle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested subtitle" do
        Subtitle.stub(:find).with("37") { mock_subtitle }
        mock_subtitle.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :subtitle => {'these' => 'params'}
      end

      it "assigns the requested subtitle as @subtitle" do
        Subtitle.stub(:find) { mock_subtitle(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:subtitle).should be(mock_subtitle)
      end

      it "redirects to the subtitle" do
        Subtitle.stub(:find) { mock_subtitle(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(subtitle_url(mock_subtitle))
      end
    end

    describe "with invalid params" do
      it "assigns the subtitle as @subtitle" do
        Subtitle.stub(:find) { mock_subtitle(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:subtitle).should be(mock_subtitle)
      end

      it "re-renders the 'edit' template" do
        Subtitle.stub(:find) { mock_subtitle(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subtitle" do
      Subtitle.stub(:find).with("37") { mock_subtitle }
      mock_subtitle.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the subtitles list" do
      Subtitle.stub(:find) { mock_subtitle }
      delete :destroy, :id => "1"
      response.should redirect_to(subtitles_url)
    end
  end

end
